# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField(max_length=200, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Publication date')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('time', models.DurationField(verbose_name='Preparation time')),
                ('vege', models.BooleanField(default=False, help_text='Is it vegetarian ?', verbose_name='Vegetarian')),
            ],
        ),
        migrations.CreateModel(
            name='MenuCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('desc', models.TextField(max_length=200, verbose_name='Description')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Publication date')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='menucard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karty.MenuCard'),
        ),
    ]
