# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-06 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karty', '0003_auto_20170413_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='section',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Menu card section'),
        ),
    ]
